services:
  app:
    # restart: always
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    volumes:
      - .:/app
    tty: true
    ports:
      - 8080:8080
    # dbを先に起動する
    depends_on:
      - "db"
  db:
    image: mysql:8.0.31
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
     - 3306:3306
  panel:
    image: "adminer:latest"
    restart: always
    ports:
      - 8082:8080
volumes:
  db-data:
    driver: local