services:
  app:
    # restart: always
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/sh -c "go run main.go"
    volumes:
      - .:/app
    tty: true
    ports:
      - 8080:8080