services:
  app:
    container_name: app
    # restart: always
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/app
    environment:
      GO_ENV: development
      DB_HOST: go-test-db
      DB_PORT: 3306
      DB_USER: go_test
      DB_PASSWORD: password
      DB_NAME: go_database
      REDIS_HOST: go-test-redis
      REDIS_PORT: 6379
    tty: true
    ports:
      - 8080:8080
    networks:
      - mynetwork
    # go-test-dbを先に起動する
    depends_on:
      - "go-test-db"
  go-test-db:
    image: mysql:8.0.31
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: go_database
      TZ: 'Asia/Tokyo'
    volumes:
      - go-test-db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
     - 3306:3306
    networks:
      - mynetwork
  cache:
    image: "redis:latest"
    container_name: go-test-redis
    ports:
      - "36379:6379"
    volumes:
      - go-test-redis-data:/data
    networks:
      - mynetwork
  panel:
    image: "adminer:latest"
    # restart: always
    ports:
      - 8082:8080
    networks:
      - mynetwork
volumes:
  go-test-db-data:
  go-test-redis-data:
networks:
  mynetwork:
    external: true
