services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - .:/app
    environment:
      GO_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: go_test
      DB_PASSWORD: password
      DB_NAME: go_database
    tty: true
    ports:
      - 8080:8080
    # dbを先に起動する
    depends_on:
      - "db"
  db:
    image: mysql:8.0.31
    platform: linux/amd64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: go_test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: go_database
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      - $PWD/_tools/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
     - 3306:3306
  panel:
    image: "adminer:latest"
    restart: always
    ports:
      - 8082:8080
volumes:
  db-data:
