# -----------------------------------------
# 開発環境
FROM golang:1.18-alpine3.16 as dev

RUN apk update && apk add alpine-sdk jq mysql mysql-client

RUN mkdir /app
WORKDIR /app

COPY /go.mod ./

COPY /go.sum ./

RUN go install github.com/cosmtrek/air@latest \
  && go install github.com/k0kubun/sqldef/cmd/mysqldef@latest \
  && go install golang.org/x/tools/cmd/goimports@latest \
  && go install github.com/matryer/moq@latest \
  && go install github.com/volatiletech/sqlboiler/v4@latest \
  && go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest

RUN go mod download

EXPOSE 8080

CMD ["air", "-c", "air.toml"]
