# -----------------------------------------
# 開発環境
FROM golang:1.18-alpine3.16 as dev

RUN mkdir /app
WORKDIR /app

RUN apk update && apk add alpine-sdk && apk add jq

RUN go install github.com/go-sql-driver/mysql
RUN go install github.com/jinzhu/gorm