name: "CI"

on:
  pull_request:
    paths:
      - "**.go"
      - .github/workflows/ci.yml
    branches:
      - main

jobs:
  ci:
    name: "Run format and linter"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: generate secret key in JWT
      run: | 
        echo "${{ secrets.JWT_SECRET_KEY }}" > ./auth/certificate/secret.pem
        chmod 444 ./auth/certificate/secret.pem
        
    - name: generate public key in JWT
      run: |
        echo "${{ secrets.JWT_PUBLIC_KEY }}" > ./auth/certificate/public.pem
        chmod 444 ./auth/certificate/public.pem
